import Head from "next/head";
import Login from "../components/Login";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    // <div className="bg-black relative">
    //   <Head>
    //     <title>Web Three Chat App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <Login></Login>
    // </div>

    <div class="md:flex">
      <div class="md:flex-shrink-0">
        <img
          class="rounded-lg md:w-56"
          src="/img/shopping.jpg"
          alt="Woman paying for a purchase"
        ></img>
      </div>
      <div class="mt-4 md:mt-0 md:ml-6">
        <div class="uppercase tracking-wide text-sm text-indigo-600 font-bold">
          Marketing
        </div>
        <a
          href="/get-started"
          class="block mt-1 text-lg leading-tight font-semibold text-gray-900 hover:underline"
        >
          Finding customers for your new business
        </a>
        <p class="mt-2 text-gray-600">
          Getting a new business off the ground is a lot of hard work. Here are
          five ideas you can use to find your first customers.
        </p>
      </div>
    </div>
  );
}
